FROM python:3.11-slim
WORKDIR /SwimRank

# Copy dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app files
COPY MainApp.py .
COPY get_credentials.py .
COPY credentials.txt .
COPY static/ ./static/

# Expose Fly.io port
EXPOSE 8080

CMD ["python", "MainApp.py"]
